name: Build Arduino Sketch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Compile red
        uses: arduino/compile-sketches@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: "esp8266:esp8266:nodemcuv2"
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          libraries: |
            - name: WiFiManager
            - name: ArduinoJson
            - name: ESPDateTime
            - name: Adafruit GFX Library
            - name: Adafruit ST7735 and ST7789 Library
            - name: U8g2_for_Adafruit_GFX
            - name: DoubleResetDetector
          sketch-paths: |
            - src/rlw
          cli-compile-flags: |
            - --build-path
            - ${{ runner.temp }}/red
            - --build-properties
            - compiler.cpp.extra_flag=-DINITR=INITR_BLACKTAB
          verbose: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ runner.temp }}/red/rlw.ino.bin
          asset_name: rlw--red-v0.0.${{ github.run_number }}.bin
          asset_content_type: application/octet-stream
